<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Ardalis.Specification.EntityFrameworkCore" Version="9.3.1" />
      <PackageReference Include="MediatR" Version="13.0.0" />
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.0" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.0">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Microsoft.Extensions.Configuration" Version="9.0.10" />
      <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.9" />
      <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="9.0.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Application\Application.csproj" />
      <ProjectReference Include="..\Common\Common.csproj" />
      <ProjectReference Include="..\Domain\Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <None Remove="SqlScripts\Views\GetHorarios.sql" />
      <EmbeddedResource Include="SqlScripts\Views\GetHorarios.sql" />
      <None Remove="SqlScripts\Views\GetAlumnoCalificaciones.sql" />
      <EmbeddedResource Include="SqlScripts\Views\GetAlumnoCalificaciones.sql" />
      <None Remove="SqlScripts\Views\GetAlumnoHorario.sql" />
      <EmbeddedResource Include="SqlScripts\Views\GetAlumnoHorario.sql" />
      <None Remove="SqlScripts\Views\GetAlumnosGrupo.sql" />
      <EmbeddedResource Include="SqlScripts\Views\GetAlumnosGrupo.sql" />
      <None Remove="SqlScripts\Views\GetCarrerasInst.sql" />
      <EmbeddedResource Include="SqlScripts\Views\GetCarrerasInst.sql" />
      <None Remove="SqlScripts\Views\GetDatosAlumno.sql" />
      <EmbeddedResource Include="SqlScripts\Views\GetDatosAlumno.sql" />
      <None Remove="SqlScripts\Views\GetDatosDocente.sql" />
      <EmbeddedResource Include="SqlScripts\Views\GetDatosDocente.sql" />
      <None Remove="SqlScripts\Views\GetDocenteHorario.sql" />
      <EmbeddedResource Include="SqlScripts\Views\GetDocenteHorario.sql" />
      <None Remove="SqlScripts\Views\GetEstadoGeneralAlumno.sql" />
      <EmbeddedResource Include="SqlScripts\Views\GetEstadoGeneralAlumno.sql" />
      <None Remove="SqlScripts\Views\GetForMapa.sql" />
      <EmbeddedResource Include="SqlScripts\Views\GetForMapa.sql" />
      <None Remove="SqlScripts\Views\GetGruposDocente.sql" />
      <EmbeddedResource Include="SqlScripts\Views\GetGruposDocente.sql" />
      <None Remove="SqlScripts\Views\GetGruposPlan.sql" />
      <EmbeddedResource Include="SqlScripts\Views\GetGruposPlan.sql" />
      <None Remove="SqlScripts\Views\GetHistorialAlumno.sql" />
      <EmbeddedResource Include="SqlScripts\Views\GetHistorialAlumno.sql" />
      <None Remove="SqlScripts\Views\GetHistorialDetalle.sql" />
      <EmbeddedResource Include="SqlScripts\Views\GetHistorialDetalle.sql" />
      <None Remove="SqlScripts\Views\GetInformacionGrupo.sql" />
      <EmbeddedResource Include="SqlScripts\Views\GetInformacionGrupo.sql" />
      <None Remove="SqlScripts\Views\GetInicioAlumno.sql" />
      <EmbeddedResource Include="SqlScripts\Views\GetInicioAlumno.sql" />
      <None Remove="SqlScripts\Views\GetInicioDocente.sql" />
      <EmbeddedResource Include="SqlScripts\Views\GetInicioDocente.sql" />
      <None Remove="SqlScripts\Views\GetInicioGestion.sql" />
      <EmbeddedResource Include="SqlScripts\Views\GetInicioGestion.sql" />
      <None Remove="SqlScripts\Views\GetMapaCurricular.sql" />
      <EmbeddedResource Include="SqlScripts\Views\GetMapaCurricular.sql" />
      <None Remove="SqlScripts\Views\GetMateriasReinscripcion.sql" />
      <EmbeddedResource Include="SqlScripts\Views\GetMateriasReinscripcion.sql" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Migrations\" />
    </ItemGroup>

</Project>
